- import_tasks: _validation.yml

- name: Create the required directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0700'
  with_items:
    - '{{ http_log_dir }}'
    - '{{ http_log_config_dir }}'

- name: Copy the logrotate config file
  template:
    src: config/logrotate.conf.j2
    dest: '{{ http_log_rotate_conf_path }}'
    mode: '0600'

- name: Create a cron job for the daily log rotation
  cron:
    cron_file: http-logs
    user: root
    name: logrotate
    job: '/usr/sbin/logrotate {{ http_log_rotate_conf_path }} &> /dev/null'
    hour: 23
    minute: 59
    state: present
