- import_tasks: _validation.yml

- name: Create the required directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0700'
  with_items:
    - '{{ http_log_dir }}'
    - '{{ http_log_config_dir }}'

- name: Copy the config files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0600'
  with_items:
    - src: config/logrotate.conf.j2
      dest: '{{ http_log_logrotate_conf_path }}'

    - src: config/crontab.j2
      dest: /etc/cron.d/http-logs
