---
- name: Make sure the admin user exists
  user:
    name: '{{ admin_name }}'
    state: present
    password: "{{ admin_password|default(lookup('password', '/tmp/pass-%s-%s'|format(ansible_date_time.iso8601_basic_short, admin_name)), true) }}"
    update_password: on_create
    groups: sudo
    append: true
    shell: /bin/bash

- name: Authorize public key for logging in as the admin user
  authorized_key:
    user: '{{ admin_name }}'
    key: '{{ admin_ssh_pubkey }}'
    state: present
  when: admin_ssh_pubkey is not none
