- name: Enforce a secure umask value in PAM’s config
  lineinfile:
    path: '{{ item }}'
    regexp: '^session optional(\s+)pam_umask\.so(?:\s|$)'
    line: 'session optional\1pam_umask.so umask=0{{ secure_umask }}'
    state: present
    backrefs: true
  with_items:
    - /etc/pam.d/common-session
    - /etc/pam.d/common-session-noninteractive

- name: Enforce a secure umask value in /etc/login.defs
  lineinfile:
    path: /etc/login.defs
    regexp: '^UMASK(\s+)'
    line: 'UMASK\g<1>{{ secure_umask }}'
    state: present
    backrefs: true

- name: Enforce a secure default file mode for home directories
  lineinfile:
    path: /etc/adduser.conf
    regexp: '^DIR_MODE='
    line: 'DIR_MODE=0700'
    state: present

- name: Find the existing home directories
  find:
    paths: /home
    file_type: directory
  register: home_directories

- name: Apply a secure file mode to the existing home directories
  file:
    path: '{{ item }}'
    mode: '0700'
  with_items: "{{ ['/root'] + home_directories.files|map(attribute='path')|list }}"

- name: Find the existing user dotfiles and skeleton files
  find:
    paths: "{{ ['/root', '/etc/skel'] + home_directories.files|map(attribute='path')|list }}"
    file_type: any
    patterns: .*
    hidden: true
    depth: 1
  register: user_dotfiles

- name: Apply a secure file mode to the existing user dotfiles and skeleton files
  file:
    path: '{{ item.path }}'
    mode: '{{ item.mode|apply_umask(secure_umask) }}'
  with_items: '{{ user_dotfiles.files }}'
