- name: Set home directories’ mode to 0700 by default
  lineinfile:
    path: /etc/adduser.conf
    regexp: '^DIR_MODE='
    line: 'DIR_MODE=0700'
    state: present

- name: Enforce umask usage in PAM config
  lineinfile:
    path: '{{ item }}'
    regexp: '\spam_umask.so\s*$'
    line: 'session required pam_umask.so'
    state: present
  with_items:
    - /etc/pam.d/common-session
    - /etc/pam.d/common-session-noninteractive

- name: Enforce secure umask in login.defs
  lineinfile:
    path: /etc/login.defs
    regexp: '^UMASK\s'
    line: 'UMASK {{ umask_value }}'
    state: present

- name: Enforce secure umask in bash.bashrc
  lineinfile:
    path: /etc/bash.bashrc
    line: 'umask {{ umask_value }}'
    state: present

- name: Find skeleton user files
  find:
    path: /etc/skel
    hidden: true
  register: skeleton_user_files

- name: Find already installed user files
  find:
    path: /home
    pattern: '{{ item }}'
    hidden: true
    recurse: true
    depth: 2
  register: installed_user_files
  with_items: "{{ skeleton_user_files.files|map(attribute='path')|map('basename')|list }}"

- name: Set a more secure chmod for skeleton and installed user files
  file:
    path: '{{ item }}'
    mode: '0600'
  with_items: "{{ (installed_user_files|json_query('results[*].files[*].path') + skeleton_user_files|json_query('files[*].path'))|flatten }}"
