---
- name: Make sure the admin user exists
  user:
    name: '{{ admin_name }}'
    state: present
    uid: '{{ admin_uid }}'
    password: "{{ admin_password|default(lookup('password', '/tmp/pass-user-%s-%s'|format(ansible_date_time.iso8601_basic_short, admin_name))|password_hash('sha512'), true) }}"
    update_password: on_create
    groups: sudo
    append: true
    shell: /bin/bash

- name: Authorize public key for logging in as the admin user
  authorized_key:
    user: '{{ admin_name }}'
    key: '{{ admin_ssh_pubkey }}'
    state: present
  when: admin_ssh_pubkey is not none

- name: Create additional Linux users
  user:
    name: '{{ item.username }}'
    state: present
    uid: '{{ item.uid|default(null, true) }}'
    password: "{{ item.password|default(lookup('password', '/tmp/pass-user-%s-%s'|format(ansible_date_time.iso8601_basic_short, item.username))|password_hash('sha512'), true) }}"
    update_password: on_create
    shell: /bin/bash
  with_items: '{{ additional_users }}'
