- include_vars:
    file: ../../base/vars/main.yml

- block:
    - name: Create the daily MySQL backup job
      cron:
        name: mysql
        job: '{{ mysql_backup_script_path }} &>> {{ backup_log_path }}'
        hour: 2
        minute: 0
      when: is_mysql

    - name: Create the daily server backup job
      cron:
        name: server
        job: '{{ backup_script_path }} &>> {{ backup_log_path }}'
        hour: 2
        minute: 30

    - name: Create a job to send the daily backup log to the root user
      cron:
        name: report
        job: >
          mail --append='From: {{ root_email }}' --subject='Backup log' {{ admin_email }}
          < {{ backup_log_path }}
          &> /dev/null
        hour: 3
        minute: 0

    - name: Create the weekly backup deep check job
      cron:
        name: check
        job: >
          {{ backup_check_script_path }}
          | mail --append='From: {{ root_email }}' --subject='Backup deep check log' {{ admin_email }}
          &> /dev/null
        weekday: 1
        hour: 3
        minute: 0

    - name: Set server-related environment variables used by the cron jobs
      cron:
        env: true
        name: '{{ item.name }}'
        job: '{{ item.value }}'
      with_items:
        - { name: BACKUP_EXCLUDE_LIST_PATH, value: '{{ backup_exclude_list_path }}' }
        - { name: BACKUP_INCLUDE_LIST_PATH, value: '{{ backup_include_list_path }}' }
        - { name: BASH_ENV, value: /etc/environment }
        - { name: SHELL, value: /usr/bin/bash }

    - name: Set MySQL-related environment variables used by the cron jobs
      cron:
        env: true
        name: '{{ item.name }}'
        job: '{{ item.value }}'
      with_items:
        - { name: MYSQL_BACKUP_STORAGE_DIR, value: '{{ mysql_backup_storage_dir }}' }
        - { name: MYSQL_BACKUP_ROTATE_CONF_PATH, value: '{{ mysql_backup_rotate_conf_path }}' }
        - { name: MYSQL_DATABASE_LIST_PATH, value: '{{ mysql_database_list_path }}' }
        - { name: MYSQL_SOCKET_PATH, value: '{{ mysql_socket_path }}' }
      when: is_mysql
  module_defaults:
    cron:
      cron_file: backup
      user: root
      state: present

- name: Make the backup crontab file private
  file:
    path: /etc/cron.d/backup
    mode: '0600'
