- name: Install Restic
  apt:
    name: restic
    state: latest
    cache_valid_time: 3600

- name: Create the required directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0700'
  with_items:
    - '{{ backup_config_dir }}'
    - '{{ backup_log_dir }}'

- name: Copy the included/excluded path lists
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0600'
  with_items:
    - src: config/include.list.j2
      dest: '{{ backup_include_list_path }}'

    - src: config/exclude.list.j2
      dest: '{{ backup_exclude_list_path }}'

- name: Copy the logrotate config file
  template:
    src: config/logrotate.conf.j2
    dest: /etc/logrotate.d/backup
    mode: '0600'

- name: Copy the backup lib file
  template:
    src: lib/backup.bash
    dest: '{{ backup_lib_path }}'
    mode: '0600'

- name: Copy the backup scripts
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0700'
  with_items:
    - src: bin/backup-files.j2
      dest: '{{ backup_script_path }}'

    - src: bin/check-backup.j2
      dest: '{{ backup_check_script_path }}'

- name: Create a cron job to run the file backup script daily
  cron:
    cron_file: backup
    user: root
    name: files
    job: '{{ backup_script_path }} &> {{ backup_log_path }}'
    hour: 2
    minute: 30
    state: present

- name: Create a cron job to send the daily backup log to the root user
  cron:
    cron_file: backup
    user: root
    name: report
    job: >
      mail --subject="Backup log [$(hostname)] [$(date --iso-8601)]" root@localhost
      < {{ backup_log_path }}
      &> /dev/null
    hour: 3
    minute: 0
    state: present

- name: Create a cron job to run the monthly backup deep check (and send the report to the root user)
  cron:
    cron_file: backup
    user: root
    name: check
    job: >
      {{ backup_check_script_path }}
      | mail --subject="Backup deep check log [$(hostname)] [$(date --iso-8601)]" root@localhost
      &> /dev/null
    day: 1
    hour: 3
    minute: 30
    state: present
