- include_vars:
    file: ../../mysql/vars/main.yml

- name: Copy the MySQL backup config file
  template:
    src: config/mysql.conf.j2
    dest: '{{ backup_config_dir }}/20-mysql.mysql'
    mode: '0600'
