- include_vars:
    file: ../../base/vars/main.yml

- name: Install Restic
  apt:
    name: restic
    state: latest
    cache_valid_time: 3600

- name: Create the required directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0700'
  with_items:
    - '{{ backup_config_dir }}'
    - '{{ backup_log_dir }}'

- name: Copy the backup config files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0600'
  with_items:
    - src: config/include.list.j2
      dest: '{{ backup_include_list_path }}'

    - src: config/exclude.list.j2
      dest: '{{ backup_exclude_list_path }}'

    - src: config/logrotate.conf.j2
      dest: '{{ backup_logrotate_conf_path }}'

    - src: config/crontab.j2
      dest: /etc/cron.d/backup

- name: Copy the backup scripts
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0700'
  with_items:
    - src: bin/backup-server.j2
      dest: '{{ backup_script_path }}'

    - src: bin/check-backup.j2
      dest: '{{ backup_check_script_path }}'

    - src: bin/send-admin-email.j2
      dest: '{{ send_admin_email_script_path }}'
