- import_tasks: _validation.yml

- name: Copy the firewall script
  template:
    src: bin/firewall.j2
    dest: '{{ firewall_script_path }}'
    mode: '0700'
  notify: firewall_config_changed

- name: Copy the firewall service unit
  template:
    src: config/firewall.service.j2
    dest: /etc/systemd/system/firewall.service
    mode: '0644'
  notify: firewall_config_changed

- name: Enable the firewall service
  service:
    name: firewall
    enabled: true
