---
- name: Ensure that the main backup directory exists
  file:
    path: '{{ mysql_backup_directory }}'
    state: directory
    mode: '0700'

- name: Ensure that the database backup subdirectories exist
  file:
    path: '{{ mysql_backup_directory }}/{{ item }}'
    state: directory
    mode: '0700'
  with_items: '{{ mysql_databases }}'

- name: Ensure the database list exists
  template:
    src: config/databases.list
    dest: '{{ mysql_database_list_path }}'
    mode: '0600'

- name: Ensure the backup script exists
  template:
    src: bin/backup_mysql
    dest: '{{ mysql_backup_script_path }}'
    mode: '0700'

- name: Make sure the backups are rotated
  template:
    src: config/logrotate.conf
    dest: /etc/logrotate.d/mysql-backups
    mode: '0644'

- name: Enable automated daily backups
  cron:
    name: Automatic MySQL backups
    user: root
    cron_file: /etc/crontab
    job: /usr/local/bin/backup_mysql
    hour: '{{ mysql_backup_cron_hour }}'
    minute: '{{ mysql_backup_cron_minute }}'
