- name: Validate user-input variables
  assert:
    that:
      - user_list is iterable

- name: Validate the user list (including the admin user)
  assert:
    that:
      - item is mapping
      - item.name is defined and item.name is string and item.name is match(linux_user_regexp)
      - item.uid is defined and item.uid is integer and item.uid >= 1000
      - item.pubkey is not defined or (item.pubkey is string and item.pubkey|length)
  with_items: '{{ [admin_user] + user_list }}'
