- import_tasks: _validation.yml

- name: Create the admin user
  user:
    name: '{{ admin_user.name }}'
    state: present
    uid: '{{ admin_user.uid }}'
    password: "{{ lookup('password', linux_password_path_template|format(admin_user.name) + ' encrypt=sha512_crypt') }}"
    update_password: on_create
    groups: sudo
    append: true
    shell: /usr/bin/bash

- name: Create the regular users
  user:
    name: '{{ item.name }}'
    state: present
    uid: '{{ item.uid }}'
    password: "{{ lookup('password', linux_password_path_template|format(item.name) + ' encrypt=sha512_crypt') }}"
    update_password: on_create
    shell: /usr/bin/bash
  with_items: '{{ user_list }}'

- name: Allow public key authentication if required
  authorized_key:
    user: '{{ item.name }}'
    key: '{{ item.pubkey }}'
    state: present
  with_items: "{{ ([admin_user] + user_list)|selectattr('pubkey', 'defined') }}"

- name: Make sure root SSH login is not directly possible anymore
  file:
    path: /root/.ssh/authorized_keys
    state: absent

- name: Prevent the deletion of non-empty groups
  lineinfile:
    path: /etc/deluser.conf
    regexp: '^ONLY_IF_EMPTY ='
    line: 'ONLY_IF_EMPTY = 1'
    state: present
