- include_vars:
    file: ../../_globals/vars/main.yml
    name: globals

- import_tasks: _validation.yml

- name: Create the admin user
  user:
    name: '{{ admin_user.name }}'
    state: present
    password: "{{ lookup('password', user_password_path_template|format(admin_user.name) + ' encrypt=sha512_crypt') }}"
    update_password: on_create
    shell: /usr/bin/bash
    comment: ''
    groups:
      - adm
      - sudo
  notify: admin_user_created

- name: Create the regular users
  user:
    name: '{{ item.name }}'
    state: present
    password: "{{ lookup('password', user_password_path_template|format(item.name) + ' encrypt=sha512_crypt') }}"
    update_password: on_create
    shell: /usr/bin/bash
    comment: ''
  with_items: '{{ user_list }}'

- name: Allow public key authentication if specified
  authorized_key:
    user: '{{ item.name }}'
    key: '{{ item.authorized_key }}'
    state: present
  with_items: "{{ ([admin_user] + user_list)|selectattr('authorized_key', 'defined') }}"
