---
- name: Define mailer host name
  lineinfile:
    path: /etc/mailname
    line: '{{ ansible_fqdn }}'
    state: present
    create: true

- name: Tweak Postfix config to make it a send-only relay
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    backrefs: true
    state: present
  with_items:
    -
      regexp: '^#?\s*myorigin\s*='
      line: 'myorigin = /etc/mailname'
    -
      regexp: '^#?\s*myhostname\s*='
      line: 'myhostname = {{ ansible_fqdn }}'
    -
      regexp: '^#?\s*mydestination\s*=(.*)'
      line: '#mydestination =\1'
    -
      regexp: '^#?\s*relayhost\s*=(.*)'
      line: '#relayhost =\1'
    -
      regexp: '^#?\s*inet_interfaces\s*='
      line: 'inet_interfaces = loopback-only'
    -
      regexp: '^#?\s*relay_transport\s*='
      line: 'relay_transport = $default_transport'
  notify: postfix_config_changed

- name: Redirect postmaster and root e-mails to custom address
  lineinfile:
    path: /etc/aliases
    regexp: '^root:'
    line: 'root: {{ postmaster_redirect_address }}'
    state: present
  notify: aliases_changed

- name: Automatically update/clean package cache
  lineinfile:
    path: /etc/apt/apt.conf.d/10periodic
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  with_items:
    -
      regexp: '^APT::Periodic::Download-Upgradeable-Packages\s'
      line: 'APT::Periodic::Download-Upgradeable-Packages "1";'
    -
      regexp: '^APT::Periodic::AutocleanInterval\s'
      line: 'APT::Periodic::AutocleanInterval "7";'

- name: Tweak unattended upgrades
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
    backrefs: true
  with_items:
    -
      regexp: '^(?://)?(\s*)"\$\{distro_id\}:\$\{distro_codename\}-updates";'
      line: '\1"${distro_id}:${distro_codename}-updates";'
    -
      regexp: '^(?://)?Unattended-Upgrade::MinimalSteps\s'
      line: 'Unattended-Upgrade::MinimalSteps "true";'
    -
      regexp: '^(?://)?Unattended-Upgrade::Mail\s'
      line: 'Unattended-Upgrade::Mail "{{ postmaster_redirect_address }}";'
    -
      regexp: '^(?://)?Unattended-Upgrade::Remove-Unused-Kernel-Packages\s'
      line: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";'
    -
      regexp: '^(?://)?Unattended-Upgrade::Remove-Unused-Dependencies\s'
      line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'

- name: Don’t delete a group if there are still users in it
  lineinfile:
    path: /etc/deluser.conf
    regexp: '^ONLY_IF_EMPTY\s*='
    line: 'ONLY_IF_EMPTY = 1'
    state: present

- name: Tweak SSH client config
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: '{{ item.regexp}}'
    line: '{{ item.line }}'
    state: present
  with_items:
    -
      regexp: '^#?\s*ForwardAgent\s'
      line: '    ForwardAgent yes'
    -
      regexp: '^#?\s*UseRoaming\s'
      line: '    UseRoaming no'

- name: Register locales
  lineinfile:
    path: /etc/locale.gen
    regexp: '^(?:#\s*)?{{ item|regex_escape }}\s+(.+)?'
    line: '{{ item }} \1'
    backrefs: true
    state: present
  with_items: '{{ installed_locales }}'
  notify: locales_changed
