---
- name: Add Docker PPA key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Register Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release|lower }} stable
    filename: docker-ce

- name: Install Docker CE
  apt:
    name: [docker-ce]
    state: latest
    force_apt_get: true

- name: Install Docker Compose
  pip:
    name: [docker-compose]
    state: latest

- name: Authorize some users to interact with the Docker daemon
  user:
    user: '{{ item }}'
    groups: docker
    append: true
  with_items: '{{ docker_users }}'
