server_timezone: Europe/Paris
server_hostname: vagrant.local

installed_locales:
  - en_US.UTF-8
  - fr_FR.UTF-8

admin_email: dummy@example.org

user_list:
  - name: app
    uid: 1024

docker_users:
  - app

mysql_databases:
  - db1
  - db2

mysql_users:
  - name: steve
    owned_databases:
      - db2

  - name: stanley
    owned_databases:
      - db1
      - db2

backup_included_path:
  - /var/backups/mysql/
  - /var/log/
  - /home/vagrant/

backup_excluded_path:
  - /var/log/journal/
  - /var/log/syslog
  - /var/log/lastlog
  - .ansible/
  - .cache/
  - .ssh/
  - .*_history
  - .viminfo
