- name: Disable backports
  replace:
    path: /etc/apt/sources.list
    regexp: '^(deb .+ {{ ansible_distribution_release }}-backports )'
    replace: '# \1'
  register: source_list

- name: Update the package cache if needed
  apt:
    update_cache: true
  when: source_list is changed

- name: Remove some bloat
  apt:
    name:
      - snapd
      - ufw
    state: absent

- name: Upgrade the installed packages (+ clean up unused packages)
  apt:
    upgrade: safe
    autoclean: true
    autoremove: true
    cache_valid_time: 3600

- name: Install some essential packages
  apt:
    name:
      - bash-completion
      - bzip2
      - ca-certificates
      - curl
      - gnupg
      - gzip
      - mailutils
      - python3
      - python3-apt
      - python3-pip
      - tar
      - unattended-upgrades
      - unzip
      - update-notifier-common
      - vim
    state: latest
    cache_valid_time: 3600

- name: Upgrade essential Python packages
  pip:
    name:
      - pip
      - setuptools
      - virtualenv
    state: latest

- name: Periodically auto-download upgradable packages and clean the package cache
  lineinfile:
    path: /etc/apt/apt.conf.d/10periodic
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  with_items:
    - regexp: '^APT::Periodic::Download-Upgradeable-Packages '
      line: 'APT::Periodic::Download-Upgradeable-Packages "1";'

    - regexp: '^APT::Periodic::AutocleanInterval '
      line: 'APT::Periodic::AutocleanInterval "7";'

- name: Tweak unattended upgrades’ config
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
    insertafter: "{{ item.insertafter|default('EOF') }}"
  with_items:
    - regexp: '^(?://)?\t"\$\{distro_id\}:\$\{distro_codename\}-updates";$'
      line: "\t\"${distro_id}:${distro_codename}-updates\";"

    - regexp: '^(?://)?Unattended-Upgrade::Mail '
      line: 'Unattended-Upgrade::Mail "{{ admin_email }}";'

    - regexp: '^(?://)?Unattended-Upgrade::Sender '
      line: 'Unattended-Upgrade::Sender "{{ root_email }}";'
      insertafter: '^Unattended-Upgrade::Mail '

    - regexp: '^(?://)?Unattended-Upgrade::MailReport '
      line: 'Unattended-Upgrade::MailReport "always";'

    - regexp: '^(?://)?Unattended-Upgrade::Automatic-Reboot '
      line: 'Unattended-Upgrade::Automatic-Reboot "true";'

    - regexp: '^(?://)?Unattended-Upgrade::Automatic-Reboot-Time '
      line: 'Unattended-Upgrade::Automatic-Reboot-Time "04:00";'

    - regexp: '^(?://)?Unattended-Upgrade::Update-Days '
      line: 'Unattended-Upgrade::Update-Days {"Sunday"};'
      insertafter: '^Unattended-Upgrade::Automatic-Reboot-Time '
