- name: Check the stat of the theoretical timezone file
  stat:
    path: /usr/share/zoneinfo/{{ server_timezone }}
  register: timezone_file_stat

- name: Validate user-input variables
  assert:
    that:
      - timezone_file_stat.stat.exists
      - installed_locales is iterable
      - admin_email_address is string and admin_email_address|length

- name: Validate the locale list
  assert:
    that:
      - item is string and item is match('^[a-z]{2}_[A-Z]{2}(?:\.[A-Z\d\-]+)?$')
  with_items: '{{ installed_locales }}'
