- name: Restart sshd
  listen: sshd_config_changed
  service:
    name: ssh
    state: restarted

- name: Require a system reboot
  listen: firewall_config_changed
  file:
    path: /var/run/reboot-required
    state: touch
    mode: '0644'
